import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Anish Next JS Learning Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
      <style jsx>
        {`   .test{
          color : red;
        }  `}
      </style>
    
        <center className='mt-5 test'><h4>
          Here i'm Learn Next js for further Projects
        </h4></center>

        <div className='box-parent mt-4'>
          <div className="card mx-2">
            <img src="https://www.shutterstock.com/image-photo/woman-caucasian-hand-gesture-showing-260nw-1751922260.jpg" className="card-img-top" alt="..." />
            <div className="card-body">
              <h5 className="card-title">Card title</h5>
              <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" className="btn btn-primary">Go somewhere</a>
            </div>
          </div>

          <div className="card mx-2">
            <img src="https://www.shutterstock.com/image-photo/woman-caucasian-hand-gesture-showing-260nw-1751922260.jpg" className="card-img-top" alt="..." />
            <div className="card-body">
              <h5 className="card-title">Card title</h5>
              <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" className="btn btn-primary">Go somewhere</a>
            </div>
          </div>

          <div className="card mx-2">
            <img src="https://www.shutterstock.com/image-photo/woman-caucasian-hand-gesture-showing-260nw-1751922260.jpg" className="card-img-top" alt="..." />
            <div className="card-body">
              <h5 className="card-title">Card title</h5>
              <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" className="btn btn-primary">Go somewhere</a>
            </div>
          </div>

          <div className="card mx-2">
            <img src="https://www.shutterstock.com/image-photo/woman-caucasian-hand-gesture-showing-260nw-1751922260.jpg" className="card-img-top" alt="..." />
            <div className="card-body">
              <h5 className="card-title">Card title</h5>
              <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" className="btn btn-primary">Go somewhere</a>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
